openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://127.0.0.1:8700
  description: Generated server url
paths:
  /api/v1/logs:
    post:
      tags:
      - log-controller
      summary: Log a message
      operationId: log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogMessage'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LogMessage'
components:
  schemas:
    LogMessage:
      type: object
      properties:
        id:
          type: string
        service:
          type: string
        level:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
