openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8200
  description: Generated server url
paths:
  /api/v1/messages:
    post:
      tags:
      - message-controller
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageModel'
        required: true
      responses:
        "200":
          description: OK
  /api/v1/messages/{id}:
    delete:
      tags:
      - message-controller
      operationId: deleteMessage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    patch:
      tags:
      - message-controller
      operationId: markAsRead
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/v1/messages/{userId}:
    get:
      tags:
      - message-controller
      operationId: getMessages
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageModel'
components:
  schemas:
    MessageModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        senderId:
          type: integer
          format: int64
        toUserId:
          type: integer
          format: int64
        text:
          type: string
        timestamp:
          type: integer
          format: int64
        read:
          type: boolean
